import { type Axis } from '../shared/types';

export type UserInputs = {
    link_0_direction: Axis;
    link_0_length: number;
    joint1_direction: Axis;
    theta1: number;
    link_1_direction: Axis;
    link_1_length: number;
    joint2_direction: Axis;
    theta2: number;
    link_2_direction: Axis;
    link_2_length: number;
    joint3_direction: Axis;
    theta3: number;
    link_3_direction: Axis;
    link_3_length: number;
    joint4_direction: Axis;
    theta4: number;
    link_4_direction: Axis;
    link_4_length: number;
    joint5_direction: Axis;
    theta5: number;
    link_5_direction: Axis;
    link_5_length: number;
    joint6_direction: Axis;
    theta6: number;
    link_6_direction: Axis;
    link_6_length: number;
};

export type StructuralParams = {
    link_0_direction: Axis;
    link_0_length: number;
    joint1_direction: Axis;
    link_1_direction: Axis;
    link_1_length: number;
    joint2_direction: Axis;
    link_2_direction: Axis;
    link_2_length: number;
    joint3_direction: Axis;
    link_3_direction: Axis;
    link_3_length: number;
    joint4_direction: Axis;
    link_4_direction: Axis;
    link_4_length: number;
    joint5_direction: Axis;
    link_5_direction: Axis;
    link_5_length: number;
    joint6_direction: Axis;
    link_6_direction: Axis;
    link_6_length: number;
};